urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


from ctt import commonviews, inscripciones, matriculas, fecha_evaluaciones, adm_periodos, pro_horarios, pro_asistencias, \
    pro_planificacion, \
    adm_mallas, pro_aperturaclase, alu_automatricula, pro_clases, alu_finanzas, alu_notas, pro_evaluaciones, \
    alu_asistencias, alu_horarios, \
    alu_cursoscomplementarios, adm_caja, alu_materias, finanzas, adm_facturas, printdoc, adm_recibopago, \
    adm_notacredito, adm_valecaja, adm_recibo_caja, \
    adm_transferencias, adm_depositos, adm_tecnologicouniversidad, adm_depositoinscripcion, adm_carreras, api, mailbox, \
    adm_coordinaciones, \
    adm_institucion, adm_colegios, adm_cursoscomplementarios, adm_evaluaciones, niveles, administrativos, \
    adm_asignaturas, adm_modelosevaluativos, docentes, \
    adm_calculofinanzas, adm_pagosnivel, servicios, gestion_servicios, registroexterno, ver_servicios, \
    adm_ordenestrabajo

from ctt import commonviews, inscripciones, matriculas, fecha_evaluaciones, adm_periodos, pro_horarios, pro_asistencias, \
    pro_planificacion, \
    adm_mallas, pro_aperturaclase, alu_automatricula, pro_clases, alu_finanzas, alu_notas, pro_evaluaciones, \
    alu_asistencias, alu_horarios, \
    alu_cursoscomplementarios, adm_caja, alu_materias, finanzas, adm_facturas, printdoc, adm_recibopago, \
    adm_notacredito, adm_valecaja, adm_recibo_caja, \
    adm_transferencias, adm_depositos, adm_tecnologicouniversidad, adm_depositoinscripcion, adm_carreras, api, mailbox, \
    adm_coordinaciones, \
    adm_institucion, adm_colegios, adm_cursoscomplementarios, adm_evaluaciones, niveles, administrativos, \
    adm_asignaturas, adm_modelosevaluativos, docentes, \
    adm_calculofinanzas, adm_pagosnivel, adm_cliente, cli_finanzas

import django.views.static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', commonviews.panel),
    path('login', commonviews.login_user),
    path('logout', commonviews.logout_user),
    path('cu', commonviews.changeuser),
    path('cudu', commonviews.changeuserdu),
    path('cambiocoordinacion', commonviews.cambiocoordinacion),
    path('cambioperiodo', commonviews.cambioperiodo),
    path('account', commonviews.account),
    path('pass', commonviews.passwd),

    # path('adm_generacionbancos', adm_generacionbancos.view),
    # INSCRIPCIONES Y MATRICULAS d
    path('inscripciones', inscripciones.view),
    path('matriculas', matriculas.view),

    path('fecha_evaluaciones', fecha_evaluaciones.view),
    path('adm_periodos', adm_periodos.view),
    path('administrativos', administrativos.view),
    path('docentes', docentes.view),
    # PROFESORES
    path('pro_clases', pro_clases.view),
    path('pro_horarios', pro_horarios.view),
    path('pro_asistencias', pro_asistencias.view),
    path('pro_evaluaciones', pro_evaluaciones.view),


    path('pro_planificacion', pro_planificacion.view),



    path('pro_aperturaclase', pro_aperturaclase.view),


    path('alu_automatricula', alu_automatricula.view),
    path('alu_asistencias', alu_asistencias.view),

    path('alu_horarios', alu_horarios.view),

    path('alu_materias', alu_materias.view),
    path('alu_notas', alu_notas.view),

    path('alu_finanzas', alu_finanzas.view),
    path('cli_finanzas', cli_finanzas.view),

    path('adm_asignaturas', adm_asignaturas.view),
    path('adm_mallas', adm_mallas.view),
    path('adm_carreras', adm_carreras.view),
    path('adm_coordinaciones', adm_coordinaciones.view),


    path('alu_cursoscomplementarios', alu_cursoscomplementarios.view),




    path('adm_caja', adm_caja.view),
    path('finanzas', finanzas.view),
    path('adm_facturas', adm_facturas.view),
    path('adm_recibopago', adm_recibopago.view),
    path('adm_notacredito', adm_notacredito.view),
    path('adm_valecaja', adm_valecaja.view),
    path('adm_recibo_caja', adm_recibo_caja.view),
    path('adm_transferencias', adm_transferencias.view),
    path('adm_depositos', adm_depositos.view),
    path('adm_depositoinscripcion', adm_depositoinscripcion.view),
    path('adm_modelosevaluativos', adm_modelosevaluativos.view),


    # GESTION DE EVALUACION DE DOCENTES
    # API FOR THIRD PARTY APPS
    path('api', api.view),
    # ESTADISTICAS Y GRAFICOS
    # BIBLIOTECA

    # IMPRESION NEW STYLE
    # path(r'^print/(^<referencia>.+)/(^<idd>\d+)', printdoc.view),
    # url(r'^print/(?P<referencia>.+)/(?P<idd>\d+)$', 'ctt.printdoc.view'),
    path('print/<str:referencia>/<int:idd>', printdoc.view, name='printdoc-view'),

    # ESTUDIANTES CON BECA ASIGNADA (BECARIOS)

    # CALENDARIO DE ACTIVIDADES

    # CARRERAS
    path('adm_carreras', adm_carreras.view),
    # VINCULACION

    # PASANTIAS DE ESTUDIANTES

    path('mailbox', mailbox.view),
    # BOLSA LABORAL

    path('adm_institucion', adm_institucion.view),

    path('adm_cursoscomplementarios', adm_cursoscomplementarios.view),



    # COLEGIOS E INSTITUCIONES
    path('adm_colegios', adm_colegios.view),
    path('adm_tecnologicouniversidad', adm_tecnologicouniversidad.view),
    path('niveles', niveles.view),
    # PROYECTO INVESTIGACION



    #BECA EMERGENTE
    # path('personalprorrogafinanciamiento', personalprorrogafinanciamiento.view),
    # EVALUADORES

    # EXAMEN DE ORIENTACION PROFESIONAL



    path('adm_evaluaciones', adm_evaluaciones.view),
    path('adm_pagosnivel', adm_pagosnivel.view),
    path('adm_cliente', adm_cliente.view),
    path('servicios', servicios.view),
    path('gestion_servicios', gestion_servicios.view),
    path('registroexterno', registroexterno.view),
    path('ver_servicios', ver_servicios.view),
    path('adm_ordenestrabajo', adm_ordenestrabajo.view),



    # INVESTIGACION MEDICINA

    # LABORATORIOS


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ctt/forms.py
# coding=utf-8
import os
from datetime import datetime, timedelta, date

from django import forms
from django.contrib.auth.models import Group
from django.core.validators import EmailValidator
from django.db.models import Q
from django.forms.models import ModelChoiceField
from django.forms.widgets import DateTimeInput
from django.utils.safestring import mark_safe
from decimal import Decimal

from settings import FORMA_PAGO_RECIBOCAJAINSTITUCION, ALUMNOS_GROUP_ID, FORMA_PAGO_NOTA_CREDITO, MAXIMO_MATERIA_ONLINE, \
    NIVEL_MALLA_UNO, CANTIDAD_MATRICULAS_MAXIMAS, EMAIL_INSTITUCIONAL_AUTOMATICO_ESTUDIANTES, EMAIL_INSTITUCIONAL_AUTOMATICO_DOCENTES,\
    FORMA_PAGO_CTAXCRUZAR, CAJAS_DEPOSITOS

from ctt.models import Persona, Canton, Malla, Nivel, Periodo, Materia, Profesor, Turno, Sexo, Provincia, Carrera, \
    Modalidad, Sesion, DIAS_CHOICES, Periodicidad, Nacionalidad, Pais, Parroquia, TipoSangre, Raza, \
    NacionalidadIndigena, \
    PersonaEstadoCivil, TiposMalla, Asignatura, TipoDuraccionMalla, NivelMalla, \
    EjeFormativo, \
    AreaConocimiento, TipoMateria, CampoFormacion, AsignaturaMalla, Coordinacion, PerfilUsuario, Sede, \
    TiempoDedicacionDocente, \
    DetalleNivelTitulacion, NivelTitulacion, TipoAlias, CampoAmplioConocimiento, CampoDetalladoConocimiento, \
    CampoEspecificoConocimiento, \
    TiposBeca, TiposFinanciamientoBeca, Discapacidad, TiposIdentificacion, Inscripcion, FormaDePago, Banco, TipoCheque, \
    TipoEmisorTarjeta, \
    TipoTarjeta, ProcesadorPagoTarjeta, TipoTarjetaBanco, DiferidoTarjeta, CuentaBanco, TipoTransferencia, \
    ReciboCajaInstitucion, \
    NotaCredito, TipoPeriodo, CompetenciaGenerica, CompetenciaEspecifica, TallerPlanificacionMateria, \
    FasesActividadesArticulacion, \
    ContenidosTallerPlanificacionMateria, ClasesTallerPlanificacionMateria, TipoEstudianteCurso, LocacionesCurso, \
    LugarRecaudacion, \
    PuntoVenta, TIPOS_VALE_CAJA, TipoTecnologicoUniversidad, Cargo, TipoAula, TIPO_REQUEST_CHOICES, \
    TIPO_EMISION_FACTURA, TIPO_AMBIENTE_FACTURACION, \
    ModeloImpresion, TipoCuentaBanco, TipoColegio, ModeloEvaluativo, ParaleloMateria, TipoCostoCurso, TIPOS_PAGO_NIVEL, \
    MateriaCursoEscuelaComplementaria, \
    Aula, CursoEscuelaComplementaria, Locacion, OPCIONES_DESCUENTO_CURSOS, TIPOS_APROBACION_PROTOCOLO, TipoProfesor, \
    TipoIntegracion, CodigoEvaluacion, IvaAplicado, Cliente, Factura, EspacioFisico, ServicioCatalogo, TipoServicio, \
    Proforma


# Servicio,


class BaseForm(forms.Form):
    formbase = forms.CharField(widget=forms.HiddenInput(), required=False)
    formtype = forms.CharField(widget=forms.HiddenInput(), required=False)
    formwidth = forms.CharField(widget=forms.HiddenInput(), required=False)

    def __init__(self, *args, **kwargs):
        # ajaxformdinamicbs.html / ajaxformbs.html
        formbase = kwargs.pop('formbase', 'ajaxformbs.html')
        formtype = kwargs.pop('formtype', 'horizontal')
        formwidth = kwargs.pop('formwidth', 'lg')
        super(BaseForm, self).__init__(*args, **kwargs)
        self.fields['formbase'].initial = formbase
        self.fields['formtype'].initial = formtype
        self.fields['formwidth'].initial = formwidth
        for field in self.fields:
            if field not in ['formwidth', 'formtype', 'formbase']:
                if 'class' in self.fields[field].widget.attrs:
                    if 'selectorfecha' in self.fields[field].widget.attrs['class']:
                        self.fields[field].initial = datetime.now().date()
        self.extra_paramaters()

    def extra_paramaters(self):
        pass

    def form_base(self):
        return self.fields['formbase'].initial

    def screenwidth_width(self):
        return int(self.fields['screenwidth'].initial)

    def eliminar(self, nombre):
        if nombre in self.fields:
            del self.fields[nombre]


class CheckboxSelectMultipleCustom(forms.CheckboxSelectMultiple):
    def render(self, *args, **kwargs):
        output = super(CheckboxSelectMultipleCustom, self).render(*args, **kwargs)
        output = '<input type="text" class="busqueda_multiselect" value="" id="id_'+kwargs['name']+'_filtro" name="'+kwargs['name']+'_filtro" ide="'+kwargs['name']+'">' + output
        output = output.replace('<label for="id_'+kwargs['name'], '<label class="contenido_'+kwargs['name']+'" for="id_'+kwargs['name'])
        output = output.replace('<div id="id_'+kwargs['name'], '<div class="custom-multiselect form-control-multiselect" style="max-height: 150px; overflow-y: scroll" id="id_control_'+kwargs['name'])
        output = output + '<input type="text" class="inputmultiselect" value="" id="id_' + kwargs['name'] + '_validacion" name="' + kwargs['name'] + '_validacion" basename="' + kwargs['name'] + '" style="display: none">'
        return mark_safe(output)


class ExtFileField(forms.FileField):

    def __init__(self, *args, **kwargs):
        self.ext_whitelist = kwargs.pop("ext_whitelist", None)
        self.filetypes = [i.lower() for i in self.ext_whitelist]
        self.filesize = kwargs.pop("max_upload_size", None)
        super(ExtFileField, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):
        upload = super(ExtFileField, self).clean(*args, **kwargs)
        if upload:
            size = upload.size
            filename = upload.name
            ext = os.path.splitext(filename)[1]
            ext = ext.lower()
            if size == 0 or ext not in self.filetypes or size > self.filesize:
                raise forms.ValidationError("Tipo de fichero o tamaño no permitido!")


def deshabilitar_campo(form, campo):
    form.fields[campo].widget.attrs['readonly'] = True
    form.fields[campo].widget.attrs['disabled'] = True



class PersonaForm(BaseForm):
    nombre1 = forms.CharField(label=u'1er Nombre', max_length=50, required=False, widget=forms.TextInput())
    nombre2 = forms.CharField(label=u'2do Nombre', max_length=50, required=False, widget=forms.TextInput())
    apellido1 = forms.CharField(label=u"1er apellido", max_length=50, required=False, widget=forms.TextInput())
    apellido2 = forms.CharField(label=u"2do apellido", max_length=50, required=False, widget=forms.TextInput())
    cedula = forms.CharField(label=u"Cédula", max_length=10, required=False, widget=forms.TextInput())
    pasaporte = forms.CharField(label=u"Pasaporte", max_length=15, required=False, widget=forms.TextInput())
    nacimiento = forms.DateField(label=u"Fecha nacimiento", required=False, input_formats=['%d-%m-%Y'], widget=DateTimeInput(format='%d-%m-%Y', attrs={'class': 'selectorfecha', 'onkeydown': 'return false;'}))
    nacionalidad = forms.ModelChoiceField(label=u"Nacionalidad", queryset=Nacionalidad.objects.all(), required=False, widget=forms.Select())
    paisnac = forms.ModelChoiceField(label=u"País de nacimiento", queryset=Pais.objects.all(), required=False, widget=forms.Select())
    provincianac = forms.ModelChoiceField(label=u"Provincia de nacimiento", queryset=Provincia.objects, required=False, widget=forms.Select())
    cantonnac = forms.ModelChoiceField(label=u"Cantón de nacimiento", queryset=Canton.objects, required=False, widget=forms.Select())
    parroquianac = forms.ModelChoiceField(label=u"Parroquia de nacimiento", queryset=Parroquia.objects, required=False, widget=forms.Select())
    sexo = forms.ModelChoiceField(label=u"Género", queryset=Sexo.objects.all(), widget=forms.Select())
    pais = forms.ModelChoiceField(label=u"País de residencia", queryset=Pais.objects.all(), required=False, widget=forms.Select())
    provincia = forms.ModelChoiceField(label=u"Provincia de residencia", queryset=Provincia.objects.all().order_by('nombre'), required=False, widget=forms.Select())
    canton = forms.ModelChoiceField(label=u"Cantón de residencia", queryset=Canton.objects.order_by('nombre'), required=False, widget=forms.Select())
    parroquia = forms.ModelChoiceField(label=u"Parroquia de residencia", queryset=Parroquia.objects.all().order_by('nombre'), required=False, widget=forms.Select())
    sector = forms.CharField(label=u"Sector", max_length=100, required=False, widget=forms.TextInput())
    direccion = forms.CharField(label=u"Calle principal", max_length=100, required=False, widget=forms.TextInput())
    direccion2 = forms.CharField(label=u"Calle secundaria", max_length=100, required=False, widget=forms.TextInput())
    referencia = forms.CharField(label=u"Referencia", max_length=100, required=False, widget=forms.TextInput())
    num_direccion = forms.CharField(label=u"Número de residencia", max_length=15, required=False, widget=forms.TextInput())
    telefono = forms.CharField(label=u"Teléfono móvil", max_length=50, required=False, widget=forms.TextInput())
    telefono_conv = forms.CharField(label=u"Teléfono fijo", max_length=50, required=False, widget=forms.TextInput())
    email = forms.CharField(label=u"Correo electrónico", max_length=200, required=False, widget=forms.TextInput())
    blog = forms.CharField(label=u"Blog", max_length=200, required=False, widget=forms.TextInput())
    twitter = forms.CharField(label=u"Twitter", max_length=200, required=False, widget=forms.TextInput())
    emailinst = forms.CharField(label=u"Correo institucional", max_length=200, required=False, widget=forms.TextInput())
    sangre = forms.ModelChoiceField(label=u"Tipo de sangre", queryset=TipoSangre.objects.all().order_by('sangre'), required=False, widget=forms.Select())
    etnia = forms.ModelChoiceField(label=u'Etnia', queryset=Raza.objects, required=False, widget=forms.Select())
    nacionalidadindigena = forms.ModelChoiceField(label=u'Nacionalidad Indígena', queryset=NacionalidadIndigena.objects, required=False, widget=forms.Select())
    estadocivil = forms.ModelChoiceField(label=u'Estado civil', queryset=PersonaEstadoCivil.objects, required=False, widget=forms.Select())

templates/cli_finanzas/adddeposito.html
{% extends "formbs.html" %}
{% block extrajavascript %}
    <script type="text/javascript">
        $(function() {
            verifica_archivo(document.getElementById('id_archivo'));
            $("#id_fecha").datepicker({format:"dd-mm-yyyy"});
            $("#id_fecha, #id_cuentabanco, #id_referencia").addClass("validate[required]");

            $("#id_deposito").click(function(){
                if ($("#id_deposito").prop('checked')){
                    $("#id_transferencia").prop('checked', false);
                } else {
                    $("#id_transferencia").prop('checked', true);
                }
             });

            $("#id_transferencia").click(function(){
                if ($("#id_transferencia").prop('checked')){
                    $("#id_deposito").prop('checked', false);
                } else {
                    $("#id_deposito").prop('checked', true);
                }
             });

            $("#id_valor").blur(function(){
                numerico($(this), 0, 0, 2);
             }).addClass("validate[min[0.01]]");

            $("#id_ventanilla").click(function(){
                if ($("#id_ventanilla").prop('checked')){
                    $("#id_movilweb").prop('checked', false);
                }
             });

            $("#id_movilweb").click(function(){
                if ($("#id_movilweb").prop('checked')){
                    $("#id_ventanilla").prop('checked', false);
                }
             });
        });
    </script>
{% endblock %}
{% block titulo %}{{ title }}{% endblock %}
{% block atras%}/alu_finanzas{% endblock %}
{% block formaction %}/alu_finanzas{% endblock %}
{% block formdestination %}/alu_finanzas{% endblock %}
{% block formextra %}
    <input type='hidden' name='action' value='adddeposito'/>
{% endblock %}
{% block formback %}/alu_finanzas{% endblock %}

templates/cli_finanzas/del.html
{% extends "ajaxdeletedinamicbs.html" %}
{% block titulo %}{{ title }}{% endblock %}
{% block formdestination %}/alu_finanzas{% endblock %}
{% block formaction %}/alu_finanzas{% endblock %}
{% block formactionvalue %}del{% endblock %}
{% block formobjectid %}{{ deposito.id }}{% endblock %}
{% block formobjectname %}el deposito o transferencia{% endblock %}
{% block formobjectrepr %}{{ deposito }}{% endblock %}

templates/cli_finanzas/observaciones.html
<tr>
    <td>{{ deposito.observaciones }}</td>
</tr>

templates/cli_finanzas/otrosdatos.html
<div class="wpwl-label wpwl-label-custom" style="display:inline-block; width: 100%">Tipo Tarjeta:  </div>
<div class="wpwl-wrapper wpwl-wrapper-custom" style="display:inline-block; width: 100%">
    <select name="customParameters[SHOPPER_tipotarjeta]" id="tipotarjeta" style="width: 100%">
        {% for b in tipotarjeta %}
            <option value="{{ b.id }}" {% if b.id == pago_tarjeta_nacional_id %}selected{% endif %}>{{ b }}</option>
        {% endfor %}
    </select>
</div>
<br>
<div class="wpwl-label wpwl-label-custom" style="display:inline-block; width: 100%">Banco:  </div>
<div class="wpwl-wrapper wpwl-wrapper-custom" style="display:inline-block; width: 100%">
    <select name="customParameters[SHOPPER_banco]" id="bancos" style="width: 100%">
        {% for b in bancos %}
            <option class="{% if otros_bancos_externos_id == b.id %}externo{% else %}nacional{% endif %}" value="{{ b.id }}">{{ b }}</option>
        {% endfor %}
    </select>
</div>
<br>
<div class="wpwl-label wpwl-label-custom" style="display:inline-block; width: 100%">Tipo Tarjeta Banco:  </div>
<div class="wpwl-wrapper wpwl-wrapper-custom" style="display:inline-block; width: 100%; margin-bottom: 10px">
    <select name="customParameters[SHOPPER_tipotarjetabanco]" id="tipotarjetabanco" style="width: 100%">
        {% for b in tipo %}
            <option value="{{ b.id }}" dif="{% if b.difiere %}1{% else %}0{% endif %}">{{ b }}</option>
        {% endfor %}
    </select>
</div>
<div class="wpwl-label wpwl-label-custom diferidos" {% if not permite_diferir %}style="display:none"{% endif %}>Numero de cuotas:  </div>
<div class="wpwl-wrapper wpwl-wrapper-custom diferidos" style="display:{% if not permite_diferir %}none{% endif %}; margin-bottom: 5px">
    <select name="recurring.numberOfInstallments" id="cantidadcuotas">
        <option value="0" selected>0</option>
    </select>
</div>
<div class="wpwl-label wpwl-label-custom" style="display:none">Tipo credito:</div>
<div class="wpwl-wrapper wpwl-wrapper-custom" style="display:none;">
    <input type="hidden" id="tipocredito" name="customParameters[SHOPPER_TIPOCREDITO]" value="00">
</div>
{#<div class="wpwl-label wpwl-label-custom" style="display:none">Intereses:</div>#}
{#<div class="wpwl-wrapper wpwl-wrapper-custom" style="display:none;">#}
{#    <select name="customParameters[SHOPPER_interes]" id="intereses">#}
{#        <option value="0">No</option>#}
{#        <option value="1">Si</option>#}
{#    </select>#}
{#</div>#}
<script type="text/javascript">
    $(function() {

        verificar_tipo = function () {
            var valor = parseInt($("#tipotarjeta").val());
            if (valor == {{ pago_tarjeta_nacional_id }}){
                $("#bancos").val(0);
                $(".externo").hide();
                $(".nacional").show();
            } else {
                $("#bancos").val({{ otros_bancos_externos_id }});
                $(".externo").show();
                $(".nacional").hide();
            }
        };

        $("#tipotarjeta").change(function () {
            verificar_tipo();
            {% if permite_diferir %}
                verifica_diferido();
            {% endif %}
        });

        {% if permite_diferir %}
            $("#bancos").change(function () {
                verifica_diferido();
            });
        {% endif %}

        verifica_diferido = function () {
            $("#cantidadcuotas").empty().append("<option value='0'>0</option>").val(0);
            $("#intereses").val(0);
            $(".diferidos").hide();
            var id = $("#bancos").val();
            var idtb = $("#tipotarjetabanco").val();
            var idt = $("[name='paymentBrand']").val();
            $("#tipocredito").val('00');
            bloqueointerface();
            $.ajax({
                type: "POST",
                url: "/alu_finanzas",
                data: {'action': 'permitediferir', 'id': id, 'idt': idt, 'idtb': idtb, 'csrfmiddlewaretoken': csrftoken},
                success: function(data) {
                    desbloqueointerface();
                    if (data.result == 'ok') {
                        $("#cantidadcuotas").empty();
                        for (item in data.lista){
                            var txt = ((data.lista[item][1]==0) ? 'Sin intereses' : 'Con intereses');
                            $("#cantidadcuotas").append("<option id='dif_"+data.lista[item][0]+"' value='"+data.lista[item][0]+"' dif='"+data.lista[item][2]+"' tipocred='"+data.lista[item][4]+"' interes='"+data.lista[item][1]+"'>"+data.lista[item][3]+" - "+txt+"</option>");
                        }
                        if (data.lista.length > 1){
                            $(".diferidos").show();
                        }
                    }
                },
                error: function() {
                    desbloqueointerface();
                },
                dataType: "json"
            });
        };

        verificar_tipo();
        {% if permite_diferir %}
            verifica_diferido();

            $("[name='paymentBrand']").change(function () {
                verifica_diferido();
            });

            $("#tipotarjetabanco").change(function () {
                verifica_diferido();
            });
/*
            $("#cantidadcuotas").change(function () {
                var valorcuotas = parseInt($(this).val());
                var dif = parseInt($("#dif_"+valorcuotas).attr('dif'));
                var interes = $(this).attr('interes');
                if (interes == 'true'){
                    $("#intereses").val(1);
                } else {
                    $("#intereses").val(0);
                }
            });
  */
            $("#cantidadcuotas").change(function () {
                    var elemento = $("#cantidadcuotas").find(":selected");
                    var interes = parseInt(elemento.attr('interes'));
                    /*
                    var gracia = parseInt(elemento.attr('gracia'));
                     */

                    {#if (interes==1) {#}
                    {#    $("#intereses").val(1);#}
                    {# } else {#}
                    {#    $("#intereses").val(0);#}
                    {# }#}

                    $("#tipocredito").val(elemento.attr('tipocred'));

                    /*
                    if (gracia) {
                        $("#gracia").val(1);
                    } else {
                        $("#gracia").val(0);
                    }
                     */
                });
        {% endif %}
    });
</script>

templates/cli_finanzas/resultado.html
{% extends "basebs.html" %}
{% block heading %}
    <script type="text/javascript">
        $(function() {
        });
    </script>
{% endblock %}
{% block atras %}/alu_finanzas{% endblock %}
{% block headcanvas %}
<div class='row'>
    <div class='col-2'>
    </div>
    <div class='col-8'>
        {% if autorizacion.aprobada %}
        <div class="alert alert-success">
            <h4 class="alert-heading">Transacción procesada exitosamente</h4><br>
            {% autoescape on %}
            <h5>El pago de los valores fue procesado sin errores, podrá consultar su comprobante en la sesión de facturas, en caso de que haya pagado valores pre facturados podrá consultar su comprobante en la sección de recibos.</h5>
            {% endautoescape %}
        </div>
        {% else %}
        <div class="alert alert-info">
            <h4 class="alert-heading">Información:</h4><br>
            <h4>
                Por razones de seguridad, queremos informarle que solo tendrá tres (3) intentos antes de que su tarjeta quede bloqueada por 30 dias.
                <br>
                Le recomendamos que lea detenidamente el mensaje enviado por su entidad financiera (mensaje siguiente), <br>verifique sus credenciales y asegúrese de ingresarlas correctamente en su próximo intento para evitar el bloqueo de su tarjeta con nuestra institución.
            </h4>
        </div>
        <div class="alert alert-danger">
            <h3 class="alert-heading">Error al procesar la transacción</h3><br>
            {% autoescape on %}
            <h3>Mensaje emitido por su ENTIDAD FINANCIERA:</h3><br>
            <h3>{{ autorizacion.mensaje }}</h3>
            {% endautoescape %}
        </div>
        {% endif %}
        <div style="place-items: center;margin: auto">
            <a href="/alu_finanzas" class="btn btn-warning btn-large">VER FINANZAS</a>
        </div>
    </div>
</div>
{% endblock %}