urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


from ctt import commonviews, inscripciones, matriculas, fecha_evaluaciones, adm_periodos, pro_horarios, pro_asistencias, \
    pro_planificacion, \
    adm_mallas, pro_aperturaclase, alu_automatricula, pro_clases, alu_finanzas, alu_notas, pro_evaluaciones, \
    alu_asistencias, alu_horarios, \
    alu_cursoscomplementarios, adm_caja, alu_materias, finanzas, adm_facturas, printdoc, adm_recibopago, \
    adm_notacredito, adm_valecaja, adm_recibo_caja, \
    adm_transferencias, adm_depositos, adm_tecnologicouniversidad, adm_depositoinscripcion, adm_carreras, api, mailbox, \
    adm_coordinaciones, \
    adm_institucion, adm_colegios, adm_cursoscomplementarios, adm_evaluaciones, niveles, administrativos, \
    adm_asignaturas, adm_modelosevaluativos, docentes, \
    adm_calculofinanzas, adm_pagosnivel, servicios, gestion_servicios, registroexterno, ver_servicios, \
    adm_ordenestrabajo

from ctt import commonviews, inscripciones, matriculas, fecha_evaluaciones, adm_periodos, pro_horarios, pro_asistencias, \
    pro_planificacion, \
    adm_mallas, pro_aperturaclase, alu_automatricula, pro_clases, alu_finanzas, alu_notas, pro_evaluaciones, \
    alu_asistencias, alu_horarios, \
    alu_cursoscomplementarios, adm_caja, alu_materias, finanzas, adm_facturas, printdoc, adm_recibopago, \
    adm_notacredito, adm_valecaja, adm_recibo_caja, \
    adm_transferencias, adm_depositos, adm_tecnologicouniversidad, adm_depositoinscripcion, adm_carreras, api, mailbox, \
    adm_coordinaciones, \
    adm_institucion, adm_colegios, adm_cursoscomplementarios, adm_evaluaciones, niveles, administrativos, \
    adm_asignaturas, adm_modelosevaluativos, docentes, \
    adm_calculofinanzas, adm_pagosnivel, adm_cliente, cli_finanzas

import django.views.static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', commonviews.panel),
    path('login', commonviews.login_user),
    path('logout', commonviews.logout_user),
    path('cu', commonviews.changeuser),
    path('cudu', commonviews.changeuserdu),
    path('cambiocoordinacion', commonviews.cambiocoordinacion),
    path('cambioperiodo', commonviews.cambioperiodo),
    path('account', commonviews.account),
    path('pass', commonviews.passwd),

    # path('adm_generacionbancos', adm_generacionbancos.view),
    # INSCRIPCIONES Y MATRICULAS d
    path('inscripciones', inscripciones.view),
    path('matriculas', matriculas.view),

    path('fecha_evaluaciones', fecha_evaluaciones.view),
    path('adm_periodos', adm_periodos.view),
    path('administrativos', administrativos.view),
    path('docentes', docentes.view),
    # PROFESORES
    path('pro_clases', pro_clases.view),
    path('pro_horarios', pro_horarios.view),
    path('pro_asistencias', pro_asistencias.view),
    path('pro_evaluaciones', pro_evaluaciones.view),


    path('pro_planificacion', pro_planificacion.view),



    path('pro_aperturaclase', pro_aperturaclase.view),


    path('alu_automatricula', alu_automatricula.view),
    path('alu_asistencias', alu_asistencias.view),

    path('alu_horarios', alu_horarios.view),

    path('alu_materias', alu_materias.view),
    path('alu_notas', alu_notas.view),

    path('alu_finanzas', alu_finanzas.view),
    path('cli_finanzas', cli_finanzas.view),

    path('adm_asignaturas', adm_asignaturas.view),
    path('adm_mallas', adm_mallas.view),
    path('adm_carreras', adm_carreras.view),
    path('adm_coordinaciones', adm_coordinaciones.view),


    path('alu_cursoscomplementarios', alu_cursoscomplementarios.view),




    path('adm_caja', adm_caja.view),
    path('finanzas', finanzas.view),
    path('adm_facturas', adm_facturas.view),
    path('adm_recibopago', adm_recibopago.view),
    path('adm_notacredito', adm_notacredito.view),
    path('adm_valecaja', adm_valecaja.view),
    path('adm_recibo_caja', adm_recibo_caja.view),
    path('adm_transferencias', adm_transferencias.view),
    path('adm_depositos', adm_depositos.view),
    path('adm_depositoinscripcion', adm_depositoinscripcion.view),
    path('adm_modelosevaluativos', adm_modelosevaluativos.view),


    # GESTION DE EVALUACION DE DOCENTES
    # API FOR THIRD PARTY APPS
    path('api', api.view),
    # ESTADISTICAS Y GRAFICOS
    # BIBLIOTECA

    # IMPRESION NEW STYLE
    # path(r'^print/(^<referencia>.+)/(^<idd>\d+)', printdoc.view),
    # url(r'^print/(?P<referencia>.+)/(?P<idd>\d+)$', 'ctt.printdoc.view'),
    path('print/<str:referencia>/<int:idd>', printdoc.view, name='printdoc-view'),

    # ESTUDIANTES CON BECA ASIGNADA (BECARIOS)

    # CALENDARIO DE ACTIVIDADES

    # CARRERAS
    path('adm_carreras', adm_carreras.view),
    # VINCULACION

    # PASANTIAS DE ESTUDIANTES

    path('mailbox', mailbox.view),
    # BOLSA LABORAL

    path('adm_institucion', adm_institucion.view),

    path('adm_cursoscomplementarios', adm_cursoscomplementarios.view),



    # COLEGIOS E INSTITUCIONES
    path('adm_colegios', adm_colegios.view),
    path('adm_tecnologicouniversidad', adm_tecnologicouniversidad.view),
    path('niveles', niveles.view),
    # PROYECTO INVESTIGACION



    #BECA EMERGENTE
    # path('personalprorrogafinanciamiento', personalprorrogafinanciamiento.view),
    # EVALUADORES

    # EXAMEN DE ORIENTACION PROFESIONAL



    path('adm_evaluaciones', adm_evaluaciones.view),
    path('adm_pagosnivel', adm_pagosnivel.view),
    path('adm_cliente', adm_cliente.view),
    path('servicios', servicios.view),
    path('gestion_servicios', gestion_servicios.view),
    path('registroexterno', registroexterno.view),
    path('ver_servicios', ver_servicios.view),
    path('adm_ordenestrabajo', adm_ordenestrabajo.view),



    # INVESTIGACION MEDICINA

    # LABORATORIOS


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ctt/forms.py
# coding=utf-8
import os
from datetime import datetime, timedelta, date

from django import forms
from django.contrib.auth.models import Group
from django.core.validators import EmailValidator
from django.db.models import Q
from django.forms.models import ModelChoiceField
from django.forms.widgets import DateTimeInput
from django.utils.safestring import mark_safe
from decimal import Decimal

from settings import FORMA_PAGO_RECIBOCAJAINSTITUCION, ALUMNOS_GROUP_ID, FORMA_PAGO_NOTA_CREDITO, MAXIMO_MATERIA_ONLINE, \
    NIVEL_MALLA_UNO, CANTIDAD_MATRICULAS_MAXIMAS, EMAIL_INSTITUCIONAL_AUTOMATICO_ESTUDIANTES, EMAIL_INSTITUCIONAL_AUTOMATICO_DOCENTES,\
    FORMA_PAGO_CTAXCRUZAR, CAJAS_DEPOSITOS

from ctt.models import Persona, Canton, Malla, Nivel, Periodo, Materia, Profesor, Turno, Sexo, Provincia, Carrera, \
    Modalidad, Sesion, DIAS_CHOICES, Periodicidad, Nacionalidad, Pais, Parroquia, TipoSangre, Raza, \
    NacionalidadIndigena, \
    PersonaEstadoCivil, TiposMalla, Asignatura, TipoDuraccionMalla, NivelMalla, \
    EjeFormativo, \
    AreaConocimiento, TipoMateria, CampoFormacion, AsignaturaMalla, Coordinacion, PerfilUsuario, Sede, \
    TiempoDedicacionDocente, \
    DetalleNivelTitulacion, NivelTitulacion, TipoAlias, CampoAmplioConocimiento, CampoDetalladoConocimiento, \
    CampoEspecificoConocimiento, \
    TiposBeca, TiposFinanciamientoBeca, Discapacidad, TiposIdentificacion, Inscripcion, FormaDePago, Banco, TipoCheque, \
    TipoEmisorTarjeta, \
    TipoTarjeta, ProcesadorPagoTarjeta, TipoTarjetaBanco, DiferidoTarjeta, CuentaBanco, TipoTransferencia, \
    ReciboCajaInstitucion, \
    NotaCredito, TipoPeriodo, CompetenciaGenerica, CompetenciaEspecifica, TallerPlanificacionMateria, \
    FasesActividadesArticulacion, \
    ContenidosTallerPlanificacionMateria, ClasesTallerPlanificacionMateria, TipoEstudianteCurso, LocacionesCurso, \
    LugarRecaudacion, \
    PuntoVenta, TIPOS_VALE_CAJA, TipoTecnologicoUniversidad, Cargo, TipoAula, TIPO_REQUEST_CHOICES, \
    TIPO_EMISION_FACTURA, TIPO_AMBIENTE_FACTURACION, \
    ModeloImpresion, TipoCuentaBanco, TipoColegio, ModeloEvaluativo, ParaleloMateria, TipoCostoCurso, TIPOS_PAGO_NIVEL, \
    MateriaCursoEscuelaComplementaria, \
    Aula, CursoEscuelaComplementaria, Locacion, OPCIONES_DESCUENTO_CURSOS, TIPOS_APROBACION_PROTOCOLO, TipoProfesor, \
    TipoIntegracion, CodigoEvaluacion, IvaAplicado, Cliente, Factura, EspacioFisico, ServicioCatalogo, TipoServicio, \
    Proforma


# Servicio,


class BaseForm(forms.Form):
    formbase = forms.CharField(widget=forms.HiddenInput(), required=False)
    formtype = forms.CharField(widget=forms.HiddenInput(), required=False)
    formwidth = forms.CharField(widget=forms.HiddenInput(), required=False)

    def __init__(self, *args, **kwargs):
        # ajaxformdinamicbs.html / ajaxformbs.html
        formbase = kwargs.pop('formbase', 'ajaxformbs.html')
        formtype = kwargs.pop('formtype', 'horizontal')
        formwidth = kwargs.pop('formwidth', 'lg')
        super(BaseForm, self).__init__(*args, **kwargs)
        self.fields['formbase'].initial = formbase
        self.fields['formtype'].initial = formtype
        self.fields['formwidth'].initial = formwidth
        for field in self.fields:
            if field not in ['formwidth', 'formtype', 'formbase']:
                if 'class' in self.fields[field].widget.attrs:
                    if 'selectorfecha' in self.fields[field].widget.attrs['class']:
                        self.fields[field].initial = datetime.now().date()
        self.extra_paramaters()

    def extra_paramaters(self):
        pass

    def form_base(self):
        return self.fields['formbase'].initial

    def screenwidth_width(self):
        return int(self.fields['screenwidth'].initial)

    def eliminar(self, nombre):
        if nombre in self.fields:
            del self.fields[nombre]


class CheckboxSelectMultipleCustom(forms.CheckboxSelectMultiple):
    def render(self, *args, **kwargs):
        output = super(CheckboxSelectMultipleCustom, self).render(*args, **kwargs)
        output = '<input type="text" class="busqueda_multiselect" value="" id="id_'+kwargs['name']+'_filtro" name="'+kwargs['name']+'_filtro" ide="'+kwargs['name']+'">' + output
        output = output.replace('<label for="id_'+kwargs['name'], '<label class="contenido_'+kwargs['name']+'" for="id_'+kwargs['name'])
        output = output.replace('<div id="id_'+kwargs['name'], '<div class="custom-multiselect form-control-multiselect" style="max-height: 150px; overflow-y: scroll" id="id_control_'+kwargs['name'])
        output = output + '<input type="text" class="inputmultiselect" value="" id="id_' + kwargs['name'] + '_validacion" name="' + kwargs['name'] + '_validacion" basename="' + kwargs['name'] + '" style="display: none">'
        return mark_safe(output)


class ExtFileField(forms.FileField):

    def __init__(self, *args, **kwargs):
        self.ext_whitelist = kwargs.pop("ext_whitelist", None)
        self.filetypes = [i.lower() for i in self.ext_whitelist]
        self.filesize = kwargs.pop("max_upload_size", None)
        super(ExtFileField, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):
        upload = super(ExtFileField, self).clean(*args, **kwargs)
        if upload:
            size = upload.size
            filename = upload.name
            ext = os.path.splitext(filename)[1]
            ext = ext.lower()
            if size == 0 or ext not in self.filetypes or size > self.filesize:
                raise forms.ValidationError("Tipo de fichero o tamaño no permitido!")


def deshabilitar_campo(form, campo):
    form.fields[campo].widget.attrs['readonly'] = True
    form.fields[campo].widget.attrs['disabled'] = True



class PersonaForm(BaseForm):
    nombre1 = forms.CharField(label=u'1er Nombre', max_length=50, required=False, widget=forms.TextInput())
    nombre2 = forms.CharField(label=u'2do Nombre', max_length=50, required=False, widget=forms.TextInput())
    apellido1 = forms.CharField(label=u"1er apellido", max_length=50, required=False, widget=forms.TextInput())
    apellido2 = forms.CharField(label=u"2do apellido", max_length=50, required=False, widget=forms.TextInput())
    cedula = forms.CharField(label=u"Cédula", max_length=10, required=False, widget=forms.TextInput())
    pasaporte = forms.CharField(label=u"Pasaporte", max_length=15, required=False, widget=forms.TextInput())
    nacimiento = forms.DateField(label=u"Fecha nacimiento", required=False, input_formats=['%d-%m-%Y'], widget=DateTimeInput(format='%d-%m-%Y', attrs={'class': 'selectorfecha', 'onkeydown': 'return false;'}))
    nacionalidad = forms.ModelChoiceField(label=u"Nacionalidad", queryset=Nacionalidad.objects.all(), required=False, widget=forms.Select())
    paisnac = forms.ModelChoiceField(label=u"País de nacimiento", queryset=Pais.objects.all(), required=False, widget=forms.Select())
    provincianac = forms.ModelChoiceField(label=u"Provincia de nacimiento", queryset=Provincia.objects, required=False, widget=forms.Select())
    cantonnac = forms.ModelChoiceField(label=u"Cantón de nacimiento", queryset=Canton.objects, required=False, widget=forms.Select())
    parroquianac = forms.ModelChoiceField(label=u"Parroquia de nacimiento", queryset=Parroquia.objects, required=False, widget=forms.Select())
    sexo = forms.ModelChoiceField(label=u"Género", queryset=Sexo.objects.all(), widget=forms.Select())
    pais = forms.ModelChoiceField(label=u"País de residencia", queryset=Pais.objects.all(), required=False, widget=forms.Select())
    provincia = forms.ModelChoiceField(label=u"Provincia de residencia", queryset=Provincia.objects.all().order_by('nombre'), required=False, widget=forms.Select())
    canton = forms.ModelChoiceField(label=u"Cantón de residencia", queryset=Canton.objects.order_by('nombre'), required=False, widget=forms.Select())
    parroquia = forms.ModelChoiceField(label=u"Parroquia de residencia", queryset=Parroquia.objects.all().order_by('nombre'), required=False, widget=forms.Select())
    sector = forms.CharField(label=u"Sector", max_length=100, required=False, widget=forms.TextInput())
    direccion = forms.CharField(label=u"Calle principal", max_length=100, required=False, widget=forms.TextInput())
    direccion2 = forms.CharField(label=u"Calle secundaria", max_length=100, required=False, widget=forms.TextInput())
    referencia = forms.CharField(label=u"Referencia", max_length=100, required=False, widget=forms.TextInput())
    num_direccion = forms.CharField(label=u"Número de residencia", max_length=15, required=False, widget=forms.TextInput())
    telefono = forms.CharField(label=u"Teléfono móvil", max_length=50, required=False, widget=forms.TextInput())
    telefono_conv = forms.CharField(label=u"Teléfono fijo", max_length=50, required=False, widget=forms.TextInput())
    email = forms.CharField(label=u"Correo electrónico", max_length=200, required=False, widget=forms.TextInput())
    blog = forms.CharField(label=u"Blog", max_length=200, required=False, widget=forms.TextInput())
    twitter = forms.CharField(label=u"Twitter", max_length=200, required=False, widget=forms.TextInput())
    emailinst = forms.CharField(label=u"Correo institucional", max_length=200, required=False, widget=forms.TextInput())
    sangre = forms.ModelChoiceField(label=u"Tipo de sangre", queryset=TipoSangre.objects.all().order_by('sangre'), required=False, widget=forms.Select())
    etnia = forms.ModelChoiceField(label=u'Etnia', queryset=Raza.objects, required=False, widget=forms.Select())
    nacionalidadindigena = forms.ModelChoiceField(label=u'Nacionalidad Indígena', queryset=NacionalidadIndigena.objects, required=False, widget=forms.Select())
    estadocivil = forms.ModelChoiceField(label=u'Estado civil', queryset=PersonaEstadoCivil.objects, required=False, widget=forms.Select())

templates/registroexterno/registro.html
{% extends "formbs.html" %}
{% load ctt_extras %}
{% block extrajavascript %}
    <script type="text/javascript">
        $(function () {
            $("#id_apellido1, #id_nombre1, #id_email, #id_comoseinformo").addClass("validate[required]");

            $("#id_nacimiento,#id_personacontacto,#id_telefonocontacto,#id_emailcontacto").addClass("validate[required]");
            $("#fieldset_ruc,#fieldset_nombreempresa,#fieldset_emailempresa,#fieldset_direccionempresa,#fieldset_telefonoempresa").hide()
            $("#fieldset_titulo_cedula,#fieldset_titulo_personacontacto").show()

            empresa = function () {
                if ($("#id_empresa").is(':checked')) {
                    $("#fieldset_ruc,#fieldset_nombreempresa,#fieldset_emailempresa,#fieldset_direccionempresa,#fieldset_telefonoempresa,#fieldset_titulo_ruc").show()
                } else {
                    $("#fieldset_ruc,#fieldset_nombreempresa,#fieldset_emailempresa,#fieldset_direccionempresa,#fieldset_telefonoempresa,#fieldset_titulo_ruc").hide()
                }
            };

            empresa();

            $("#id_empresa").click(function () {
                empresa();
            });

            // Aplicar estilos sólo a este formulario
            $('form').first().addClass('form-publico-inscripcion');

            // Opcional: título amigable arriba (si formbs no lo pinta como quieres)
            $('.breadcrumbs, .page-header').remove(); // si te estorban migas
            // Puedes jugar con esto según la estructura real del template base.



            verifica_tipo_identificacion = function () {
                no_existe();
                $("#id_cedula, #id_pasaporte").val('');
                if (parseInt($("#id_tipoidentificacion").val()) === 1) {
                    $("#fieldset_cedula").show();
                    $("#fieldset_pasaporte").hide();
                    $("#id_cedula").addClass("validate[required,cedula]").val('');
                    $("#id_pasaporte").removeClass("validate[required]").val('');

                } else {
                    $("#fieldset_cedula").hide();
                    $("#fieldset_pasaporte").show();
                    $("#id_pasaporte").addClass("validate[required]").val('');
                    $("#id_cedula").removeClass("validate[required,cedula]").val('');
                }
            };

            $("#id_tipoidentificacion").change(function () {
                verifica_tipo_identificacion();
            });

        });

        validarcedula = function () {
            var valor = $("#id_cedula").val().trim();
            $("#id_cedula").val(valor);
            if (valor.length > 0) {
                $("#id_cedula").addClass("validate[required,cedula]");
                bloqueointerface();
                $.ajax({
                    type: "POST",
                    url: "/api",
                    data: {'a': 'datosexternospersona', 'cedula': valor},
                    success: function (data) {
                        desbloqueointerface();
                        if (data.result === 'ok') {
                            datosconsulta = data;
                            $("#id_nombre1").val(data['nombre1']);
                            $("#id_nombre2").val(data['nombre2']);
                            $("#id_apellido1").val(data['apellido1']);
                            $("#id_apellido2").val(data['apellido2']);
                            $('#id_direccion').val(data['calledomicilio'])
                            $('#id_telefono').val(data['celular'])
                            $('#id_email').val(data['email'])
                            // datos factura
                            var value1 = $('#id_nombre1').val();
                            var value2 = $('#id_nombre2').val();
                            var value3 = $('#id_apellido1').val();
                            var value4 = $('#id_apellido2').val();
                            $("#id_personacontacto").val(value1 + " " + value2 + " " + value3 + " " + value4);


                            if ($('#id_sexo')) {
                                if ('idsexo' in data) {
                                    $('#id_sexo').val((data['idsexo']));
                                }
                            }

                            if ($('#id_direccion')) {
                                if ('calledomicilio' in data) {
                                    $('#id_direccion').val(data['calledomicilio']);
                                }
                            }

                            if ($('#id_telefono')) {
                                if ('celular' in data) {
                                    $('#id_telefono').val(data['celular']);
                                }
                            }

                            if ($('#id_email')) {
                                if ('email' in data) {
                                    $('#id_email').val(data['email']);
                                }
                            }

                        }
                    },
                    error: function () {
                        desbloqueointerface();
                    },
                    dataType: "json"
                });
            } else {
                $("#id_cedula").removeClass("validate[required,cedula]");
            }
        };

        $("#id_cedula").change(function () {
            validarcedula();
        });

        let contactoEditado = false;

        $('#id_telefonocontacto').on('input', function () {
            contactoEditado = true;  // el usuario ya lo tocó, deja de sobreescribir
        });

        $('#id_telefono').on('input', function () {
            if (!contactoEditado || $('#id_telefonocontacto').val().trim() === '') {
                $('#id_telefonocontacto').val($(this).val());
            }
        });

        let emailEditado = false;

        $('#id_emailcontacto').on('input', function () {
            emailEditado = true;  // el usuario ya lo tocó, deja de sobreescribir
        });

        $('#id_email').on('input', function () {
            if (!emailEditado || $('#id_emailcontacto').val().trim() === '') {
                $('#id_emailcontacto').val($(this).val());
            }
        });



        validarruc = function () {
            var valor = $("#id_ruc").val().trim();
            $("#id_ruc").val(valor);
            if (valor.length === 13) {
                bloqueointerface();
                $.ajax({
                    type: "POST",
                    url: "/api",
                    data: {'a': 'datosempresa', 'ruc': valor},
                    success: function (data) {
                        desbloqueointerface();
                        if (data.result === 'ok') {
                            datosconsulta = data;
                            $("#id_nombreempresa").val(data['nombre']);
                            $("#id_direccionempresa").val(data['direccion']);
                            $("#id_telefonoempresa").val(data['celular']);
                        }
                    },
                    error: function () {
                        desbloqueointerface();
                    },
                    dataType: "json"
                });
            }else{
                  NotificacionAlerta('warning','RUC invalido','Tiene que ingresar un RUC')
            }
        };

        $("#id_ruc").change(function () {
            validarruc();
        });

    </script>

    <style>
        /* Fondo general un poco más suave */
        body {
            background-color: #f5f5f9;
        }

        /* Card principal del formulario */
        .form-publico-inscripcion {
            max-width: 960px;
            margin: 2rem auto 3rem;
            background: #ffffff;
            border-radius: 14px;
            padding: 2.5rem 2rem;
            box-shadow: 0 18px 40px rgba(15, 23, 42, .12);
        }

        /* Título del formulario */
        .form-publico-inscripcion-title {
            font-size: 1.4rem;
            font-weight: 700;
            margin-bottom: 1rem;
            color: #1f2933;
        }

        .form-publico-inscripcion-subtitle {
            font-size: 0.95rem;
            color: #6b7280;
            margin-bottom: 1.5rem;
        }

        /* Cada fila de campo (usa la estructura de formbs: fieldset/control-label/control) */
        .form-publico-inscripcion fieldset.control-group {
            border: 0;
            margin: 0 0 .9rem 0;
            padding: 0;
            display: flex;
            align-items: center;
            gap: 1.25rem;
        }

        .form-publico-inscripcion .control-label.label-text {
            float: none !important;
            width: 30% !important;
            text-align: right;
            padding-right: 0 !important;
            display: flex;
            align-items: center;
            justify-content: flex-end;
            height: auto !important;
        }

        .form-publico-inscripcion .control-label.label-text label {
            font-weight: 600;
            font-size: 0.95rem;
            color: #111827;
        }

        .form-publico-inscripcion .control {
            float: none !important;
            width: 70% !important;
        }

        /* Inputs, selects, etc. */
        .form-publico-inscripcion input[type="text"],
        .form-publico-inscripcion input[type="email"],
        .form-publico-inscripcion input[type="tel"],
        .form-publico-inscripcion input[type="number"],
        .form-publico-inscripcion input[type="date"],
        .form-publico-inscripcion select,
        .form-publico-inscripcion textarea {
            width: 100% !important;
            max-width: 100%;
            border-radius: 8px;
            border: 1px solid #d1d5db;
            padding: 0.45rem 0.75rem;
            font-size: 0.95rem;
            transition: border-color .15s ease, box-shadow .15s ease;
        }

        .form-publico-inscripcion input:focus,
        .form-publico-inscripcion select:focus,
        .form-publico-inscripcion textarea:focus {
            outline: none;
            border-color: #4f46e5;
            box-shadow: 0 0 0 1px rgba(79, 70, 229, .25);
        }

        /* Secciones (Datos personales, contacto, etc. si luego quieres agrupar) */
        .form-section-title {
            font-size: 1.05rem;
            font-weight: 600;
            color: #374151;
            margin: 1.2rem 0 .4rem;
        }

        .form-section-divider {
            border: none;
            border-top: 1px solid #e5e7eb;
            margin: 0 0 1rem 0;
        }

        /* Bloque de términos y nota final */
        .form-terminos-wrapper {
            margin-top: 1.5rem;
            background: #f9fafb;
            border-radius: 10px;
            padding: 1rem 1rem 0.5rem;
            border: 1px solid #e5e7eb;
        }

        .form-terminos-wrapper p {
            margin-bottom: 0.25rem;
            font-size: 0.9rem;
            color: #4b5563;
        }

        .form-terminos-wrapper a {
            text-decoration: underline;
        }

        /* Botón principal */
        .form-publico-inscripcion .btn-form {
            padding: 0.6rem 2.5rem;
            font-size: 1rem;
            border-radius: 999px;
            font-weight: 600;
        }

        /* Versión móvil */
        @media (max-width: 768px) {
            .form-publico-inscripcion {
                padding: 1.5rem 1.25rem;
                margin-top: 1rem;
            }

            .form-publico-inscripcion fieldset.control-group {
                display: block;
            }

            .form-publico-inscripcion .control-label.label-text {
                width: 100% !important;
                text-align: left;
                justify-content: flex-start;
                margin-bottom: 0.25rem;
            }

            .form-publico-inscripcion .control {
                width: 100% !important;
            }
        }
    </style>

{% endblock %}
{% block titulo %}{% endblock %}
{% block formaction %}/registroexterno{% endblock %}
{% block formdestination %}/registroexterno?action=registrook{% endblock %}
{% block formextra %}
    <input type='hidden' name='action' value='registro'/>
    <input type='hidden' name='key' value='{{ key }}'/>
    <input type='hidden' name='numero' value='{{ numero }}'/>
{% endblock %}
{% block formsuffix %}
    {% if usa_capcha %}
        {# tu fieldset del captcha tal como está, ya toma los nuevos estilos #}
    {% endif %}

    <div class="form-terminos-wrapper">
        <input class="form-check-input validate[required]" type="checkbox" value="" name="terminos" id="terminos">
        <span style="font-size: medium">
                Acepta nuestras
                <a href="https://www.indoamerica.edu.ec/politicas-de-confidencialidad-universidad-indoamerica/"
                   target="_blank">
                    Políticas de Uso de Datos
                </a>
                y
                <a href="https://www.indoamerica.edu.ec/clausula-de-proteccion-de-datos/" target="_blank">
                    Cláusula de protección de datos
                </a>
            </span>
        </p>
        <p>
            *El usuario y contraseña seran enviados a los correos de contacto que ingreso, y que pueda hacer uso de
            nuestra plataforma.
        </p>
    </div>

    <div style="place-items: center;margin: 1.5rem auto 0; width: 100%">
        <p style="text-align: center; margin-bottom: 0">
            <a href="javascript:;" class="btn btn-success btn-form" id="formbutton">Registrarme</a>
        </p>
    </div>
{% endblock %}